services:
  - type: web
    name: chore-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_CONTACT_EMAIL
        value: mailto:kiran@nourishednaturalhealth.com
      - key: FLASK_DEBUG
        value: "0"
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
